### ISSUE TITLE
getAccessToken fails with missing `accessToken` response property

### ISSUE THREAD

**Issue by xSAVIKx** [Finch-API/finch-api-java#264]
While the issue pointed out in https://github.com/Finch-API/finch-api-java/issues/257 is resolved I am facing a new one now. The deserialization of the `getAccessToken` always fails with:
```
Caused by: com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.tryfinch.api.client.FinchClientImpl$GetAccessTokenResponse] value failedfor JSON property accessToken due to missing (therefore NULL) value for creator parameter accessToken which is a non-nullable type
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 318] (through reference chain: com.tryfinch.api.client.FinchClientImpl$GetAccessTokenResponse["accessToken"])
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84) ~[jackson-module-kotlin-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:519) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3722) ~[jackson-databind-2.14.3.jar:2.14.3]
        at com.tryfinch.api.client.FinchClientImpl$special$$inlined$jsonHandler$1.handle(Handlers.kt:50) ~[finch-java-core-0.30.2.jar:0.30.2]
        ... 87 more
```

I'm using the latest v0.30.2 SDK.

The API call is done with:
```
String accessToken = finch.getAccessToken(
        config.getFinchClientId(),
        config.getFinchClientSecret(),
        finchAuthCode,
        null
);
```

When I debug the execution here's the Jackson details message:
```
Instantiation of [simple type, class com.tryfinch.api.client.FinchClientImpl$GetAccessTokenResponse] value failed for JSON property accessToken due to missing (therefore NULL) value for creator parameter accessToken which is a non-nullable type
```

Here's the request being sent:
<img width="453" alt="image" src="https://github.com/user-attachments/assets/57243c0f-1b0f-42c4-a012-fac37ae39aee">

And as far as I can tell the response just has empty body:
![image](https://github.com/user-attachments/assets/be3062ce-01cb-4cb5-9ad9-2d5ab3da5238)

`finch-request-id` is `9d49c760-4bfa-11ef-941f-d37b979b4aa0`.

**Comment by dgellow** [comment]
Hi @xSAVIKx,

Could you try to send the request with `curl -v` and tell us if get a valid response?

```
curl https://api.tryfinch.com/auth/token \
-X POST \
-H "Content-Type: application/json" \
--data-raw '{
    "client_id": "<your_client_id>",
    "client_secret": "<your_client_secret>",
    "code": "<your_authorization_code>",
    "redirect_uri": "https://example.com"
}'
```

See https://developer.tryfinch.com/how-finch-works/quickstart#exchange-the-authorization-code-for-an-access-token for details.

**Comment by dgellow** [comment]
We pushed a fix, it will be released with the next release: https://github.com/Finch-API/finch-api-java/pull/266

**Comment by xSAVIKx** [comment]
The response in cURL is OK. Sorry for late response, just got time to check it.

```json
{
  "company_id": "COMPANY_ID",
  "account_id": "ACCOUNT_ID",
  "provider_id": "gusto",
  "products": [
    "company",
    "directory",
    "individual",
    "employment",
    "payment",
    "pay_statement"
  ],
  "connection_type": "finch",
  "client_type": "sandbox",
  "access_token": "ACCESS_TOKEN"
}
```

**Comment by xSAVIKx** [comment]
@dgellow it's now failing with the next error:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "company_id" (class com.tryfinch.api.client.FinchClientImpl$GetAccessTokenResponse), not marked as ignorable (one known property: "access_token"])
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 319] (through reference chain: com.tryfinch.api.client.FinchClientImpl$GetAccessTokenResponse["company_id"])
```

Has anyone even tested the fixes? Do you need help setting up a simple e2e test scenario?

**Comment by dgellow** [comment]
Thanks for keeping us in the loop with your reports. We've fixed the issue you mentioned with the update in #269, it will be part of the next release.

You're right about the auth flow — the Java SDK doesn't have test coverage for that yet. We've been talking about how to tackle this, and it's on our radar. The rest of the SDK has solid test coverage with a mocked API, but the auth flow is a bit trickier.

**Comment by dgellow** [comment]
@xSAVIKx I have an update to share:
1. I sent some time reviewing Finch SDKs, `getAccessToken()` was supposed to be deprecated but for reasons hasn't been annotated as such in finch-java. That's fixed with https://github.com/Finch-API/finch-api-java/pull/272.
2. Instead you should use `client.accessTokens().create()`, you can find an example here: https://github.com/Finch-API/finch-api-java/blob/b1d464c65c5fa626ec6f03210bf5d1c9fefdc5d6/finch-java-example/src/main/java/com/tryfinch/api/example/Main.java. `accessTokens().create()` is directly codegen'ed from Finch API spec, making it more robust and better tested than `getAccessToken().
3. I also found out an issue resulting in our tests not running in CI. They would have caught the latest issue you reported — we do have some tests for `getAccessToken` (not e2e though). That has now been fixed upstream, a PR will come soon to this repo.

Could you try once more, this time with `client.accessTokens().create()`, and tell us if you encounter any issue?
